name: dockerloginDEVQA

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  LogintodockerhubDEV:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
    - uses: actions/checkout@v5
    - name: docker login
      uses: docker/login-action@v3
      with:
       username: ${{secrets.DOCKERHUBUSERNAME}}
       password: ${{secrets.DOCKERHUBPASSWORD}}

  LogintodockerhubQA:
    runs-on: ubuntu-latest
    environment: QA
    steps:
    - uses: actions/checkout@v5
    - name: docker login
      uses: docker/login-action@v3
      with:
       username: ${{secrets.DOCKERHUBUSERNAME}}
       password: ${{secrets.DOCKERHUBPASSWORD}}
